# Generated by Django 4.1.2 on 2022-12-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_follower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="followers",
            new_name="follower",
        ),
    ]
