# Generated by Django 4.1.2 on 2022-12-29 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_rename_followers_follower_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="follower",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
